### ISSUE TITLE
Little bugs in aria-Extract_tutorial.ipynb

### ISSUE THREAD

**Issue by Yuankailiu** [aria-tools/ARIA-tools-docs#25]
Recently, I went through ariaExtract_turotial notebook, and I found something that the authors may want to correct or add. 

**1. [Extract incidence Angle with shapefile](https://nbviewer.jupyter.org/github/aria-tools/ARIA-tools-docs/blob/master/JupyterDocs/ariaExtract/ariaExtract_tutorial.ipynb#3.-Extract-incidenceAngle-with-shapefile)**

In the [Extract incidence Angle with shapefile](https://nbviewer.jupyter.org/github/aria-tools/ARIA-tools-docs/blob/master/JupyterDocs/ariaExtract/ariaExtract_tutorial.ipynb#3.-Extract-incidenceAngle-with-shapefile), we use OSMnx python library to create a shapefile from the OpenStreetMap dataset. In the tutorial, there is no guidance or a cell of codes of doing that. Perhaps adding a remark of installing OSMnx by running:
 `conda install -c conda-forge osmnx`. 

Then we can run the following to download the polygon of the Big Island:
`import osmnx as ox
city = ox.gdf_from_place('Big Island, Hawaii')
ox.save_gdf_shapefile(city)
ox.plot_shape(ox.project_gdf(city))`

Then, we need to rename the downloaded files to "Big_Island.something" and put them into the folder under `./support_docs/Big_Island` which is not created by default. So, we also need to create that folder.

With that done, we can run GDAL's orginfo to verify the contents of our shapefile.

**2. [Application 1. ENU conversion factors](https://nbviewer.jupyter.org/github/aria-tools/ARIA-tools-docs/blob/master/JupyterDocs/ariaExtract/ariaExtract_tutorial.ipynb#Application-1.--ENU-conversion-factors-)**

Here we need to create a _"results"_ folder in order to put 3-band enu files generating by GDAL. So, again, we need to do `mkdir results`. Otherwise, we will have an issue later on:
> RuntimeError: Attempt to create file `results/20180502_20180408_enu' failed.

**3. [Application 2. Computing displacement map](https://nbviewer.jupyter.org/github/aria-tools/ARIA-tools-docs/blob/master/JupyterDocs/ariaExtract/ariaExtract_tutorial.ipynb#Application-2.-Computing-displacement-map-)**

The conversion from interferometric phase, 𝜑, to line‐of‐sight displacement, d, is written as: 
𝑑 = ( 4𝜋 / 𝜆 ) 𝜑
Howerver, I think it should be the following instead:
𝑑 [𝑐𝑚] = ( 𝜆 [𝑐𝑚] / 4𝜋 [𝑟𝑎𝑑] ) 𝜑 [𝑟𝑎𝑑]

These are some little things I found. Thank you.

**Comment by bbuzz31** [comment]
@Yuankailiu thanks for these findings and especially the detailed instructions. 
The latest pull request solves points 2 and 3.

In regards to point 1, we provide the Big Island shapefile in the support_docs; as long as you clone the directory as suggested in the installation instruction you will have them in your repo.
