### ISSUE TITLE
Rejected Scenes - Track 14

### ISSUE THREAD

**Issue by totaibi01** [aria-tools/ARIA-tools-docs#29]
Hello,

I faced the rejected scenes problem with track 14 when I tried to download and process ARIA products for a specific bounding box. Please find my commands below:
 
ariaDownload.py --track 14 --bbox '21 26.5 39.2 40.5'  -o download
ariaTSsetup.py -f 'products/*.nc' -b '21 26.5 39.2 40.5' --mask Download
 
I got only two interferograms out of 1220 scenes. There are two error messages:
1. Rejected scenes
2. Stitched interferograms have gaps
 
What do you suggest?
 
Thamer

**Comment by dbekaert** [comment]
Thanks for the question. Ideally better to post under the ARIA-tools repo as not sure the team looks here very much.

From looking on the ARIA-products page, there are about 1500 products on track 14 in Saudi region. For the track 14 south long, there are about 500 products, where an interferogram generally consist out of 5 products. So would expect roughly about 100 large interferograms over you AOI.

![Screen Shot 2020-05-01 at 1 55 05 PM](https://user-images.githubusercontent.com/19240905/80841003-6221a380-8bb3-11ea-9cf9-1bac70cb48cc.png)

I do not directly see if you are doing anything wrong. 
I will try to replicate your problem.

**Comment by dbekaert** [comment]
@totaibi01 i cannot reproduce.
I downloaded a subset of the data:

```
(ARIA-tools-test) MT-101939:JupyterDocs dbekaert$ ariaDownload.py --track 14 --bbox '21 26.5 39.2 40.5' -o download --start 20191001 
https://api.daac.asf.alaska.edu/services/search/param?asfplatform=Sentinel-1%20Interferogram%20(BETA)&processingLevel=GUNW_STD&output=JSON&relativeOrbit=14&bbox=39.2,21,40.5,26.5
``` 

Ran the same BBOX command TS command, which shows 25 large IDFS out of 92 products, consistent with the expectation outlined in my previous post.

```
(ARIA-tools-test) MT-101939:JupyterDocs dbekaert$ ariaTSsetup.py -f 'products/*.nc' -b '21 26.5 39.2 40.5' --mask Download
***Time-series Preparation Function:***
Shapefile ./user_bbox.shp created for input user bounds.
Multi-core version
All (92) GUNW products meet spatial bbox criteria.
Group GUNW products into spatiotemporally continuous interferograms.
All (25) interferograms are spatially continuous.
Thread count specified for gdal multiprocessing = 2
Download/cropping DEM
Downloaded 3 arc-sec SRTM DEM here: ./DEM/SRTM_3arcsec.dem

Extracting unwrapped phase, coherence, and connected components for each interferogram pair
Generating: unwrappedPhase - [=>                       4%                       ] 20191022_20191010    0s /     0sMulti-core version failed, will try single for loop
Generating: unwrappedPhase - [======================= 48%                       ] 20191221_20191127   73s /    79sMulti-core version failed, will try single for loop
Generating: unwrappedPhase - [==================================================] 20200302_20200219  170s /     7s
Generating: coherence - [==================================================] 20200302_20200219   30s /     1s

Extracting single incidence angle, look angle and azimuth angle files valid over common interferometric grid
Generating: incidenceAngle - [==================================================] 20191022_20191010 
Generating: lookAngle - [==================================================] 20191022_20191010 
Generating: azimuthAngle - [==================================================] 20191022_20191010 
Creating directory: ./stack
Number of coherence discovered:  25
[==================================================] 20200302_20200219    0s /     0s
cohStack : stack generated
Directory ./stack already exists.
Number of connectedComponents discovered:  25
[==================================================] 20200302_20200219    0s /     0s
connCompStack : stack generated
Directory ./stack already exists.
Number of unwrapped interferograms discovered:  25
[==================================================] 20200302_20200219    0s /     0s
unwrapStack : stack generated
```

Can you verify:
1) you are using latest version of the code
2) re-run the download to see if you have missing product
3) perhaps try the same subset i did

**Comment by bbuzz31** [comment]
I also cannot recreate

**Comment by totaibi01** [comment]
Hi @dbekaert 

I'm using the latest version of the code. I tried the same set and I got the following error:

`[thamer@kamb new]$ ariaTSsetup.py -f 'products/*.nc' -b '21 26.5 39.2 40.5' --mask Download
***Time-series Preparation Function:***
Shapefile ./user_bbox.shp created for input user bounds.
Multi-core version
All (92) GUNW products meet spatial bbox criteria.
Group GUNW products into spatiotemporally continuous interferograms.
All (2) interferograms are spatially continuous.
Thread count specified for gdal multiprocessing = 2
ERROR 1: PROJ: proj_identify: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_identify: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_identify: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_identify: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_identify: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
Download/cropping DEM
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
Downloaded 3 arc-sec SRTM DEM here: ./DEM/SRTM_3arcsec.dem
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed

Extracting unwrapped phase, coherence, and connected components for each interferogram pair
Generating: unwrappedPhase - [=>                       4%                       ] 20191022_20191010    0s /     1sERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/thamer/miniconda3/share/proj failed
Multi-core version failed, will try single for loop
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/thamer/ARIA-tools/tools/ARIAtools/unwrapStitching.py", line 1161, in createConnComp_Int
    write_ambiguity(connData,connDataName,connProj,connGeoTrans,connNoData)
  File "/home/thamer/ARIA-tools/tools/ARIAtools/unwrapStitching.py", line 1213, in write_ambiguity
    bnd.FlushCache()
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/osgeo/gdal.py", line 2660, in FlushCache
    return _gdal.Band_FlushCache(self, *args)
RuntimeError: PROJ: proj_create_from_name: Open of /home/thamer/miniconda3/share/proj failed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thamer/ARIA-tools/tools/ARIAtools/unwrapStitching.py", line 237, in __createImages__
    intermediateFiles = Parallel(n_jobs=-1,max_nbytes=1e6)(delayed(createConnComp_Int)(ii) for ii in all_inputs)
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/thamer/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/thamer/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: PROJ: proj_create_from_name: Open of /home/thamer/miniconda3/share/proj failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thamer/miniconda3/bin/ariaTSsetup.py", line 15, in <module>
    main(inps)
  File "/home/thamer/ARIA-tools/tools/ARIAtools/tsSetup.py", line 273, in main
    export_products(standardproduct_info.products[1], standardproduct_info.bbox_file, prods_TOTbbox, layers, dem=demfile, lat=Latitude, lon=Longitude, mask=inps.mask, outDir=inps.workdir, outputFormat=inps.outputFormat, stitchMethodType='overlap', verbose=inps.verbose, num_threads=inps.num_threads, multilooking=inps.multilooking)
  File "/home/thamer/ARIA-tools/tools/ARIAtools/extractProduct.py", line 433, in export_products
    product_stitch_overlap(unw_files,conn_files,prod_bbox_files,bounds,prods_TOTbbox, outFileUnw=outFileUnw,outFileConnComp= outFileConnComp, mask=mask,outputFormat = outputFormat,verbose=verbose)
  File "/home/thamer/ARIA-tools/tools/ARIAtools/unwrapStitching.py", line 1463, in product_stitch_overlap
    unw.UnwrapOverlap()
  File "/home/thamer/ARIA-tools/tools/ARIAtools/unwrapStitching.py", line 341, in UnwrapOverlap
    self.__createImages__()
  File "/home/thamer/ARIA-tools/tools/ARIAtools/unwrapStitching.py", line 250, in __createImages__
    intermediateFiles_temp = createConnComp_Int(inputs)
  File "/home/thamer/ARIA-tools/tools/ARIAtools/unwrapStitching.py", line 1161, in createConnComp_Int
    write_ambiguity(connData,connDataName,connProj,connGeoTrans,connNoData)
  File "/home/thamer/ARIA-tools/tools/ARIAtools/unwrapStitching.py", line 1213, in write_ambiguity
    bnd.FlushCache()
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/osgeo/gdal.py", line 2660, in FlushCache
    return _gdal.Band_FlushCache(self, *args)
RuntimeError: PROJ: proj_create_from_name: Open of /home/thamer/miniconda3/share/proj failed`

But at least I did not get the rejected scenes message! Why I had the rejected scenes problem earlier although I use the same bbox coordinates?

**Comment by dbekaert** [comment]
@totaibi01 looks like you proj is not installec correctly.
Suggest you make a clean intall to see if that removes the problem, and re-try again.

**Comment by totaibi01** [comment]
@dbekaert I reinstalled project and it works.

What do you suggest regarding the rejected scenes?

**Comment by dbekaert** [comment]
@totaibi01 Are your products still being rejected? Can you copy the output to the screen?
Earlier rejection likely has to do that not all data was available online.

**Comment by totaibi01** [comment]
Nothing rejected, but I meant the earlier rejection. Please find my screen below:

```
(base) [thamer@kamb new]$ ariaTSsetup.py -f 'products/*.nc' -b '21 26.5 39.2 40.5' --mask Download
***Time-series Preparation Function:***
Shapefile ./user_bbox.shp created for input user bounds.
Multi-core version
All (92) GUNW products meet spatial bbox criteria.
Group GUNW products into spatiotemporally continuous interferograms.
All (2) interferograms are spatially continuous.
Thread count specified for gdal multiprocessing = 2
Download/cropping DEM
Downloaded 3 arc-sec SRTM DEM here: ./DEM/SRTM_3arcsec.dem

Extracting unwrapped phase, coherence, and connected components for each interferogram pair
Generating: unwrappedPhase - [=>                       4%                       ] 20191022_20191010    0s /     0sMulti-core version failed, will try single for loop
Generating: unwrappedPhase - [===>                     8%                       ] 20191103_20191010   15s /   176sMulti-core version failed, will try single for loop
Generating: unwrappedPhase - [=========>              20%                       ] 20191115_20191022   46s /   185sMulti-core version failed, will try single for loop
Generating: unwrappedPhase - [===========>            24%                       ] 20191115_20191103   56s /   179sMulti-core version failed, will try single for loop
Generating: unwrappedPhase - [===================>    40%                       ] 20191209_20191127  103s /   155sMulti-core version failed, will try single for loop
Generating: unwrappedPhase - [======================= 48%                       ] 20191221_20191127  124s /   134sMulti-core version failed, will try single for loop
Generating: unwrappedPhase - [======================= 84% =============>        ] 20200207_20200126  245s /    46sMulti-core version failed, will try single for loop
Generating: unwrappedPhase - [======================= 88% ===============>      ] 20200219_20200126  267s /    36sMulti-core version failed, will try single for loop
Generating: unwrappedPhase - [==================================================] 20200302_20200219  307s /    12s
Generating: coherence - [==================================================] 20200302_20200219   55s /     2s

Extracting single incidence angle, look angle and azimuth angle files valid over common interferometric grid
Generating: incidenceAngle - [==================================================] 20191022_20191010
Generating: lookAngle - [==================================================] 20191022_20191010
Generating: azimuthAngle - [==================================================] 20191022_20191010
Creating directory: ./stack
Number of coherence discovered:  25
[==================================================] 20200207_20200126    0s /     0s
cohStack : stack generated
Directory ./stack already exists.
Number of connectedComponents discovered:  25
[==================================================] 20200207_20200126    0s /     0s
connCompStack : stack generated
Directory ./stack already exists.
Number of unwrapped interferograms discovered:  25
[==================================================] 20200302_20200219    0s /     0s
unwrapStack : stack generated
```

 What is the data range available online? I'm interested to process the data for the period between 2014 until 2020.

**Comment by dbekaert** [comment]
Not sure. your approach looked correct.
Unless you added additional files i do not directly see a reason why it
should have failed.

**Comment by dbekaert** [comment]
I think you just might not have downloaded all the products.
The track was only completed 2 weeks ago with missing products being added till then. 

I suggest you download all products, by re-running you download command. 
Files already downloaded will be skipped.

Triggering is done based on precise orbit which is available with a 10-20 day lag. 
Products on the website should reflect that lag.

**Comment by totaibi01** [comment]
Great, I will download them again and retry the process.

I will keep get back to you!

**Comment by totaibi01** [comment]
If I download the whole track 14, what is the proper bbox coordinates?

**Comment by dbekaert** [comment]
You can try and download the area to which you want to make your analysis on. i.e. use the box for which you want to generate the time-series for.

will close the ticket as solved.
