### ISSUE TITLE
ariaTSsetup tutorial does not cover minimumOverlap option

### ISSUE THREAD

**Issue by EJFielding** [aria-tools/ARIA-tools-docs#35]
I am trying to figure out how to use the `-mo MINIMUMOVERLAP` in  `ariaTSsetup.py` but I can't find it  documented here in the tutorials or in the main `ARIA-tools`.

**Comment by dbekaert** [comment]
Hi Eric,

This is currently not that well documented. I recall a closed issue ticket
that captures a description and example. See here:
https://github.com/aria-tools/ARIA-tools/issues/161

@rzinke @ssangha could you add the description to the ariaExtract and
tsprep notebooks?

**Comment by EJFielding** [comment]
@dbekaert Thanks for the pointer to the closed issue. I see now that the units are in km^2. I thought it might be a percentage of the bounding box, so I tried `-mo 90` thinking it would keep scenes covering 90% of the bbox, but now I see that would only keep scenes with as little as 90 km^2 of data. It would help a lot to document this.

**Comment by dbekaert** [comment]
Agreed, we will add it on the todo list. We also welcome any contributions!

**Comment by EJFielding** [comment]
I can try to add something, but I am not sure I understand the option enough yet to explain it.
Now I tried `ariaTSsetup.py -f 'products/*.nc' --bbox "26 27.5 83 86" -d download --mask download -w bbox26_27_5 -mo 15000` to make sure I only kept scenes with at least 15000 km^2 and I see that I have almost nothing left in the present Nepal coverage.
```
***Time-series Preparation Function:***
Shapefile bbox26_27_5/user_bbox.json created for input user bounds.
Multi-core version
Multi-core version failed, will try single for loop
316 out of 470 GUNW products rejected for not meeting user's bbox spatial criteria
Group GUNW products into spatiotemporally continuous interferograms.
All (143) interferograms are spatially continuous.
Thread count specified for gdal multiprocessing = 2
132 out of 143 interferograms rejected for not meeting specified spatial thresholds
```

**Comment by dbekaert** [comment]
for now ariaExtract is updated with information.

**Comment by EJFielding** [comment]
Good to hear about this update.
